### ISSUE TITLE
Missing elements from the externs, extern/implementation mismatch, partial implementations

### ISSUE THREAD

**Issue by ibilon** [openfl/openfl#1107]
List of all issues (merged here) about missing property/functions:
- [ ] `flash.events.FocusEvent.direction` (#196) note that even haxe flash externs don't have this
- [ ] `flash.text.TextField.MouseWheelEnabled` (#198)

Functions mentioned in the extern but missing from the implementation (not even with a `throw not implemented`):
- [ ] `flash.display.BitmapData.drawWithQuality` (#224)
- [ ] `flash.events.Event.EXIT_FRAME` (#1012)

Partial implementations:
- [ ] `flash.display.BitmapData.draw` blend mode support in cairo is missing `ALPHA, ERASE, INVERT, SHADER, SUBTRACT` (#286)

**Comment by jgranick** [comment]
`flash.events.FocusEvent.direction` is not a part of the Flash Player API, it is an AIR/Flash Lite API

We might discuss better support for AIR externs in the future, but otherwise this is currently outside our scope :smile:

The others have been implemented, with the exception of `bitmapData.draw` improvements, which I'm tracking here: https://github.com/openfl/openfl/issues/1412

Thanks a lot :grin:
